services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: mydb
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  # Frontend React
  frontend:
    build:
      context: ./frontend  # assumindo que o front-end está nesta pasta
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://backend:5000  # importante para chamadas API
    depends_on:
      - backend
    networks:
      - app-network
    stdin_open: true  # necessário para React em desenvolvimento
    tty: true        # necessário para React em desenvolvimento
    restart: unless-stopped

  # Banco de dados MySQL
  db:
    image: mysql:latest
    container_name: airbnb-db 
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: mydb 
    ports:
      - "3307:3306"
    volumes:
      - my-db-volume:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  my-db-volume:

networks:
  app-network:
    driver: bridge