"""Recriação do banco de dados

Revision ID: 86b2c3b35b91
Revises: 
Create Date: 2025-03-31 00:30:51.199259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b2c3b35b91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('typeUser', sa.Enum('OWNER', 'CONTRACTOR', 'BOTH', name='typeuserenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Halls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('typeHall', sa.Enum('APARTAMENT', 'HOUSE', 'HOTEL', name='typehallenum'), nullable=False),
    sa.Column('fk_owner', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['fk_owner'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_hall', sa.Integer(), nullable=False),
    sa.Column('fk_user', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELED', name='reservationstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['fk_hall'], ['Halls.id'], ),
    sa.ForeignKeyConstraint(['fk_user'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reservations')
    op.drop_table('Halls')
    op.drop_table('Users')
    # ### end Alembic commands ###
